# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='context',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 9, 6, 14, 11, 3, 226589, tzinfo=utc), verbose_name='CONTENT'),
            preserve_default=False,
        ),
    ]
