# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160906_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Data'),
        ),
    ]
